train:
    _target_: src.datasets.DLADataset
    data_dir: "/mnt/d/hse/DLA/dla_dataset"
    part: "train"
    instance_transforms: ${transforms.instance_transforms.train}
val:
    _target_: src.datasets.DLADataset
    data_dir: "/mnt/d/hse/DLA/dla_dataset"
    part: "val"
    limit: 500
    instance_transforms: ${transforms.instance_transforms.inference}
