_target_: src.model.ConvTasNet
n_audio_channels: 512
n_output_channels: 512
encoder_kernel_size: 8
encoder_padding: 8
encoder_stride: 4
decoder_kernel_size: 8
decoder_padding: 4
decoder_stride: 4
separator_kernel_size: 8
separator_size: 2
separator_count_blocks: 2
