defaults:
    - model: tdfnet
    - writer: wandb
    - metrics: avss_metrics
    - datasets: custom_dataset
    - dataloader: dataloader
    - transforms: spectrogram
    - _self_
inferencer:
  device_tensors: ["mix_audio", "video"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  from_pretrained: "/Users/antonytce/Desktop/dla_project/weights/tdfnet_best.pth"
  seed: 1
