train:
  get_spectrogram: # special key for getting spectrogram
    _target_: src.transforms.LogMelSpectrogram
    sample_rate: 16000
    n_mels: 160
    n_fft: 400
    window_fn:
      _target_: hydra.utils.get_method
      path: torch.hann_window
inference:
  get_spectrogram:
    _target_: src.transforms.LogMelSpectrogram
    sample_rate: 16000
    n_mels: 160
    n_fft: 400
    window_fn:
        _target_: hydra.utils.get_method
        path: torch.hann_window
